#!/usr/bin/env bash
# Install the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 137189-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 137189-web-02 100.25.156.195:80 check\n\tserver 137189-web-01 54.90.33.123:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
